name: short_unique_id
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/sky-train/short_unique_id

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.8
