name: short_unique_id
description: A starting point for Dart libraries or applications.
version: 1.0.1
repository: https://github.com/sky-train/short_unique_id

environment:
  sdk: ^3.0.0

dev_dependencies:
  test: 1.25.8
